"""empty message

Revision ID: 55bb5477eabb
Revises: 88b431d1a359
Create Date: 2025-04-09 22:43:29.489552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bb5477eabb'
down_revision: Union[str, None] = '88b431d1a359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ankets', 'username')
    op.add_column('likes', sa.Column('sender_id', sa.BigInteger(), nullable=False))
    op.add_column('likes', sa.Column('sender_username', sa.String(length=34), nullable=False))
    op.add_column('likes', sa.Column('recipient_id', sa.BigInteger(), nullable=False))
    op.drop_column('likes', 'recipient')
    op.drop_column('likes', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('sender', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('likes', sa.Column('recipient', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('likes', 'recipient_id')
    op.drop_column('likes', 'sender_username')
    op.drop_column('likes', 'sender_id')
    op.add_column('ankets', sa.Column('username', sa.VARCHAR(length=34), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
