"""empty message

Revision ID: 88b431d1a359
Revises: 087e169a41ea
Create Date: 2025-03-31 15:45:30.164083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b431d1a359'
down_revision: Union[str, None] = '087e169a41ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ankets', sa.Column('username', sa.String(length=34), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ankets', 'username')
    # ### end Alembic commands ###
