"""empty message

Revision ID: aa5e6f69232a
Revises: 6df0bc7ee470
Create Date: 2025-03-27 11:59:37.821692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5e6f69232a'
down_revision: Union[str, None] = '6df0bc7ee470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('file', sa.String(length=96), nullable=False),
    sa.Column('video', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ankets', sa.Column('male', sa.Boolean(), nullable=False))
    op.drop_column('ankets', 'media_type')
    op.drop_column('ankets', 'media_id')
    op.drop_column('ankets', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ankets', sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ankets', sa.Column('media_id', sa.VARCHAR(length=96), autoincrement=False, nullable=False))
    op.add_column('ankets', sa.Column('media_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('ankets', 'male')
    op.drop_table('media')
    # ### end Alembic commands ###
