"""empty message

Revision ID: dc12b0b13aac
Revises: 
Create Date: 2025-03-26 21:51:12.229641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc12b0b13aac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ankets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('interest', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('media_id', sa.String(length=96), nullable=False),
    sa.Column('media_type', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ankets')
    # ### end Alembic commands ###
